### ISSUE TITLE
window attributes errors

### ISSUE THREAD

**Issue by nsklaus** [obiwac/x-compositing-wm#1]
i wanted to try your project and ran into some issues.
i'm testing this on a devuan (chimaera), laptop is an old macbookpro from 2015.  the only missing dependencies i had was :
```
src/cwm.h:15:10: fatal error: GL/glew.h: No such file or directory
```
so i installed `sudo apt install libglew-dev` and then compile went fine. i'm testing it through xephyr, nested X session. like so:
```
 Xephyr -br -ac -reset -no-host-grab -screen 1024x768 :1 &
```
so everything i want to run is prefixed by `DISPLAY=:1`.
here's what i got:
```
[ x-compositing-wm ]
> cc src/main.c -Isrc -I/usr/local/include -L/usr/local/lib -lX11 -lGL -lGLEW -lXcomposite -lXfixes -lXinerama -lm -o x-compositing-wm

[ x-compositing-wm ]
> ls
LICENSE  pics  README.md  src  x-compositing-wm

[ x-compositing-wm ]
> DISPLAY=:1 xterm &
[4] 1297

[ x-compositing-wm ]
> DISPLAY=:1 ./x-compositing-wm 
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009

```
when i run xterm, i see a dark window appearing, but nothing is visible in it. X pointer seems to notice when i'm hovering terminal or not, the pointer changes from an "X" to a "I" ..  if i ctrl-c break x-compositing-wm, suddenly everything becomes visible. but of course x-compositing-wm process is gone. if i try to relaunch it i get:
```
[ x-compositing-wm ]
> DISPLAY=:1 ./x-compositing-wm 
XError code = 10, string = BadAccess (attempt to access private resource denied), resource ID = 0x51f
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
```
seems something is wrong with window attributes. i can run lxqt fine using the same method, through xephyr, and also other WMs too.

**Comment by obiwac** [comment]
It relies on GLX, so it won't really work through Xephyr. I can't say for sure, but I imagine the black window is because the OpenGL context is created correctly and everything (software rendering, Xephyr doesn't support hardware acceleration), but `glXCreatePixmap` fails, so the texture within the window is empty.

If you try running it directly on your current display, it should work (presumably even if you already have a regular WM running).

**Comment by nsklaus** [comment]
thanks for the reply. but for example i can run other desktop on xephyr, desktops that handle compositing correctly. like lxqt desktop, it have transparency effects, translucent menus and such.
if i cannot run it on nested Xsession, it renders the development a bit more difficult. i will try to run it normaly outside xephyr and report back.

**Comment by nsklaus** [comment]
ok, so i have tested on a normal Xsession, here's my ~/.xinitrc:
```
# ~/.xinitrc
xrandr -s 1440x900
xrandr --dpi 75
xrdb -merge ~/.Xdefaults
xrdb -merge ~/.Xresources
sxhkd &
xcompmgr &
# exec amiwm
exec /home/klaus/Sources/x-compositing-wm/x-compositing-wm
```
the problem persists, the term i launched from tty is shown all black, no text visible. the screen is blinking/flashing randomly.
i can move windows around, i tested to type in blind mode `xterm` to launch another term from the first one i had opened from tty, and it worked, another 'black term' showed up with not text visible. i could move both windows around. but there's a problem with rendering.  even when not using xephyr. 
back on my own wm, i tried to run glxgears:
```
> glxgears -info
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
GL_RENDERER   = Mesa Intel(R) Iris(R) Graphics 6100 (BDW GT3)
GL_VERSION    = 4.6 (Compatibility Profile) Mesa 20.3.5
GL_VENDOR     = Intel
GL_EXTENSIONS =  ..........

398 frames in 5.0 seconds = 79.565 FPS
300 frames in 5.0 seconds = 59.973 FPS
300 frames in 5.0 seconds = 59.970 FPS
300 frames in 5.0 seconds = 59.966 FPS
```

and also:
```
> glxinfo | grep "direct rendering"
direct rendering: Yes
```
and GL support seems installed correctly to me. i do not know why x-compositing-wm shows up with black windows. and why it is blinking/flashing white too..

**Comment by obiwac** [comment]
You shouldn't be running another compositor (`xcompmgr`) at the same time, that may be the issue here.

**Comment by nsklaus** [comment]
video of x-compositing-wm:  https://0x0.st/ocTf.mk
video of lxqt with composite test: https://0x0.st/ocTO.mkv
and now i go try to remove xcompmgr from my .xinitrc and run x-compositing-wm in normal Xsession.
i'll report back.

**Comment by nsklaus** [comment]
same problem, minus the random white flashes.
all windows are pitch black. i tried to run xterm, and qterminal too. text wasn't visible on both.

**Comment by obiwac** [comment]
Okay... Could you tell me what graphics solution you're running?

**Comment by nsklaus** [comment]
it's on the post above,
basically: macbookpro from 2015, using intel iris 6100
```
GL_RENDERER   = Mesa Intel(R) Iris(R) Graphics 6100 (BDW GT3)
GL_VERSION    = 4.6 (Compatibility Profile) Mesa 20.3.5
GL_VENDOR     = Intel
```
and:
```
> lspci
00:02.0 VGA compatible controller: Intel Corporation Iris Graphics 6100 (rev 09)
```

**Comment by obiwac** [comment]
Ah yeah sorry about that. That's quite odd as I've already tested on Intel. Around line 300 in `src/cwm.h`, could you perhaps add a few `printf`'s around `XCompositeNameWindowPixmap` & `glXCreatePixmap`? Something like this:

```c
const int pixmap_attributes[] = {
	GLX_TEXTURE_TARGET_EXT, GLX_TEXTURE_2D_EXT,
	GLX_TEXTURE_FORMAT_EXT, format, 0 // GLX_TEXTURE_FORMAT_RGB_EXT
};

printf("format %d\n", format);

Pixmap x_pixmap = XCompositeNameWindowPixmap(cwm->wm->display, window->window);
printf("x_pixmap %d\n", x_pixmap);

window_internal->pixmap = glXCreatePixmap(cwm->wm->display, config, x_pixmap, pixmap_attributes);
printf("glx_pixmap %d\n", window_internal->pixmap);
```

(Don't worry about potential warnings.)

**Comment by nsklaus** [comment]
certainly, here's what i got:
```
[ x-compositing-wm ]
> DISPLAY=:1 xterm
format 8410
x_pixmap 2097161
glx_pixmap 2097162
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x20(r0009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
XError code = 9, string = BadDrawable (invalid Pixmap or Window parameter), resource ID = 0x200009
```
note that, when i launch x-compositing-wm there is no output at all. then when i run xterm, or some other term,
that's when i start to get the ouput i pasted above.

**Comment by obiwac** [comment]
> note that, when i launch x-compositing-wm there is no output at all. then when i run xterm, or some other term, that's when i start to get the ouput i pasted above. 
 ​

Yup that's to be expected.

Try also printing something after `glXBindTexImageEXT​` and removing the call to `XFreePixmap`.

**Comment by nsklaus** [comment]
this time, the terminal was visible, and text too.
```
something                                                                                                                                   
something                                                                                                                                   
something                                                                                                                                   
something                                                                                                                                   
format 8410                                                                                                                                         
x_pixmap 2097165                                                                                                                                                        
glx_pixmap 2097166                                                                                                                                                              
something                                                                                                                                   
something                                                                                                                                   
something                                                                                                                                   
something    
```
modified source:
https://paste.ofcode.org/E4iLwH7Ej2pNNTqqNVN8kF

screenshot:
https://0x0.st/ocTl.png

also, as you can see on the screenshot above, i ran a test program of mine that shows a translucent red window. the translucency works only if i move the window (pressing mouse button and super key and moving it around). if i stop pressing key and mouse button, the red window become opaque. shouldn't it stays translucent all the time ?

**Comment by obiwac** [comment]
Huh, interesting. I didn't know the X pixmap couldn't be freed; maybe a difference in the Xorg version? Anyhow I'll commit a fix when I'm back home.

Could you show me the code you're using to create your translucent window? `x-compositing-wm` was never meant to work with translucency, and the translucency you see by dragging the window is actually just an effect applied by the WM to all windows when dragged. I can probably quite easily create a patch to get it working correctly though.

**Comment by nsklaus** [comment]
here's the code for my transparency test program:
https://paste.ofcode.org/PVHZZEaEBBFT6DMHcHbnfQ

yes, if you could make it work always that would be nice, i would like to use your project as a base to study and making WMs.
the wm i'm working on is a stacking wm, and has no support for compositing. and i would like to either add compositing support to it, or rebase my work on something small and functional to build from (so probably your project, as it make a nice small test/study case). but i need it to support translucency. i mean, idealy speaking.

**Comment by obiwac** [comment]
Everything should be working fine now. Could you confirm this?

> it make a nice small test/study case

Yup, just be sure not to take it as gospel, as this was originally supposed to be a prototype project and thus doesn't *really* use the best of coding practices in places. Another thing you may wanna check out is using XCB/EGL instead of Xlib/GLX, as it's quite a bit more modern.

**Comment by nsklaus** [comment]
thank you for the commit, and the advices :)
as you can see on this video: https://0x0.st/ocAM.mkv
it works well now. 
although, i noticed a new problem that is also visible on that video,
do you see how many terms are left opened on my blank Xsession before i start xcompositng-wm ?
when i start it, they are all being moved away, probably offscreen coordinates, i don't know, but if i start a new term, it is visible on screen, i can move it around, start my own test program and verify all worked well. but, all those 3 terms, i cannot find them back until i close xcompositing-wm. when i do that, they 'magically' appear in the middle of the screen whereas when xcompositing-wm was active, they weren't anywhere to be found.
this leads me to think, there should be a test to be made when xcompositing-wm is being started as to not move offscreen existing windows. and if it's not a coordinate offset, then those existing windows aren't getting picked up and mapped.
maybe also, a new hotkey to gather all windows and center them on screen/remap them and present them in a way each one is accessible would come as handy.
also, newly started terminal isn't placed on screen according to user resolution, here i was using 800x600, coordinates for placement of new windows could be calculated with taking the user resolution into account, to open them centered, or at least fully visible. this is for suggestions and feedback. otherwise, yes, your project will be good test case for me to learn, study and build up from. thank you for doing it.

**Comment by nsklaus** [comment]
and, i can't seem to be able to apply a background picture with `feh --bg-scale ~/Pictures/mypic.jpg` for example.
is there some special steps involved to be able to set a background picture on the root window ?

**Comment by obiwac** [comment]
Actually they're not being moved off-screen, it's just that the overlay is being rendered on top of everything. `x-compositing-wm` doesn't have any knowledge of already existing windows. It shouldn't be too hard to implement, but it's not something I'll do (you're welcome to write a PR though, if you want).

As for backgrounds, they're not supported. I'm not totally sure how they work with X as I've never really played around with them.

**Comment by nsklaus** [comment]
ok then, thank you for the answers. i will try to look into those. i'm beginner in C though, it might take me some time, studying first before i can submit a PR. for the rest, as far as i'm concerned this issue can now be closed.
